### ISSUE TITLE
Have OpenAPI parser read/apply the Ports spec under the server section of the yaml

### ISSUE THREAD

**Issue by owentl** [frikky/Shuffle#160]
**Is your feature request related to a problem? Please describe.**
this is very low priority!!

Even if the port is specified for the application in the OpenAPI YAML, Shuffle does not pick that out and use it.

**Describe the solution you'd like**
I would like to have the port(s) respected out of the yaml as the default port.  It would be nice if this could be overwritten through the UI.

**Describe alternatives you've considered**
Just specify the port in the URL, this works just fine!

**Additional context**

**Comment by frikky** [comment]
Can you share an example of how you've specified the port? Is it using the servers > variables > port? 

```
servers:
  - url: https://{customerId}.saas-app.com:{port}/v2
    variables:
      customerId:
        default: demo
        description: Customer ID assigned by the service provider
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
```
