### ISSUE TITLE
Mount permanent storage in apps from Shuffle

### ISSUE THREAD

**Issue by dadokkio** [frikky/Shuffle#205]
Hello, I was trying to add a local volume as app volume.
My evil plan was to add a volume in backend docker-compose.yml file:
```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files
      - ${LOCAL_DISK_LOCATION}:/shuffle-disk  # << HERE from .env
```
And then mount that in the app docker-compose.yml [tools in this case]:
```
version: "3.4"
services:
  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /shuffle-disk:/shuffle-disk   # << HERE from .env
```
The backend see the folder properly but the in app docker I receive error because the path does not exists.
Not sure if that is the right approach, do you have better suggestion?
